config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index', as: :t
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task

  post 'tasks', to: 'tasks#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tareas = Task.all
  end

  def show
    @tareas = Task.find(params[:id])
  end

  def new
    @tareas = Task.new
  end

  def create
    @tareas = Task.new(task_params)
    @tareas.save
    redirect_to t_path(@tareas)
  end

  def edit
  end

  def update
    @tareas = Task.find(params[:id])
    @tareas.update(task_params)
    redirect_to t_path(@tareas)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_with model: @tareas do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
  <% @tareas.each do |tarea| %>
  <li><input type="checkbox"> <%= link_to tarea.title, task_path(tarea) %></li>
  <% end %>

  <%= link_to "Add New Task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @tareas do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>
  <%= link_to "Back to list", t_path %>

app/views/tasks/show.html.erb
<h1>Details</h1>

<%= @tareas.title %>
<%= @tareas.details %>
<%= link_to "Back to list", t_path %>